sudo: false
language: node_js
node_js:
- stable
script:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_ad716207d570_key -iv $encrypted_ad716207d570_iv
  -in id_rsa.enc -out ./.travis/id_rsa -d
- mv .travis/id_rsa ~/.ssh -f
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
after_script:
- scp -o StrictHostKeyChecking=no -r public/ notroot@works.leiwangxing.com:/data/www/tkss/
- scp -o StrictHostKeyChecking=no -r dist/ notroot@works.leiwangxing.com:/data/www/tkss/
